version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: aiohttp
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: aiohttp_app
    ports:
      - 5430:5432
